export enum AuditAction {
  // Document lifecycle
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_HASHED = 'DOCUMENT_HASHED',
  DOCUMENT_DELETED = 'DOCUMENT_DELETED',

  // Land record lifecycle
  LAND_RECORD_CREATED = 'LAND_RECORD_CREATED',
  LAND_RECORD_UPDATED = 'LAND_RECORD_UPDATED',
  LAND_RECORD_DELETED = 'LAND_RECORD_DELETED',

  // Risk assessment
  RISK_INDICATOR_CREATED = 'RISK_INDICATOR_CREATED',
  RISK_INDICATOR_RESOLVED = 'RISK_INDICATOR_RESOLVED',
  RISK_SCORE_COMPUTED = 'RISK_SCORE_COMPUTED',

  // Verification workflow
  WORKFLOW_INITIATED = 'WORKFLOW_INITIATED',
  WORKFLOW_TRANSITIONED = 'WORKFLOW_TRANSITIONED',
  WORKFLOW_ANCHOR_RECORDED = 'WORKFLOW_ANCHOR_RECORDED',

  // Notifications
  NOTIFICATION_SENT = 'NOTIFICATION_SENT',
  NOTIFICATION_FAILED = 'NOTIFICATION_FAILED',
}
