export enum RiskIndicatorType {
  MISSING_FIELD = 'MISSING_FIELD',
  EXPIRED_REGISTRATION = 'EXPIRED_REGISTRATION',
  BOUNDARY_OVERLAP = 'BOUNDARY_OVERLAP',
  FORGED_SIGNATURE = 'FORGED_SIGNATURE',
  DUPLICATE_PARCEL = 'DUPLICATE_PARCEL',
  INCONSISTENT_OWNERSHIP = 'INCONSISTENT_OWNERSHIP',
  OTHER = 'OTHER',
}

export enum RiskIndicatorSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}
